# Copyright 2017 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
FROM golang:1.10
LABEL maintainer "ops@freenome.com"


COPY . /go/src/github.com/freenome/k8s-cert-generator/

RUN go install -ldflags "-linkmode=external -extldflags '-static -pthread'" github.com/freenome/k8s-cert-generator
