
[[constraint]]
  name = "github.com/micahhausler/k8s-acme-cache"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[prune]
  go-tests = true
  unused-packages = true
