
[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  version = "0.39"
  name = "github.com/kevinburke/handlers"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[prune]
  go-tests = true
  unused-packages = true
